### ISSUE TITLE
Algunos Themes no funcionan bien

### ISSUE THREAD

**Issue by ignacio-r** [Cuis-University/Cuis-University#6]
Al cambiar el theme en preferences, abrir un class browser y clickear se abre el emergency evaluator.
Los themes son los siguientes:

- SkypeTheme
- HighContrastBlackTheme
- DarkGrayTheme
- BlueTheme

![themes](https://user-images.githubusercontent.com/42122391/43689741-2ad2b7d4-98d5-11e8-9bd5-aebc10b80699.png)

**Comment by ngarbezza** [comment]
hola @ignacio-r ! Por casualidad, sabés si sigue pasando en las últimas versiones de CuisUniversity?

**Comment by ignacio-r** [comment]
Hola, está solucionado. En la versión 4365 funcionan todos los themes.
